### PR TITLE
Use types_or directive for hook instead of files

### PR DESCRIPTION
**Pull request by imomaliev**
For more information https://pre-commit.com/#config-types_or

### CODE REVIEW

**Review by thibaudcolas — COMMENTED** [review]
@imomaliev I can see what the documentation says but I don’t really see the point of this change – is there anything this improves over the `files` regular expression?

Additionally it seems that there are no predefined types for Nunjucks or Liquid files. It doesn’t seem very appealing to me to have to use a different pre-commit configuration property depending on which file type you want to lint.

**Comment by imomaliev** [comment]
Hi @thibaudcolas! `types_or` allows for more consistent hooks when run on file types that may have multiple extensions. Also if hook user wants to change files themself they will have to copy current definition and than add personal regex

>  it seems that there are no predefined types for Nunjucks or Liquid files

This could be easily changed with PR to  https://github.com/pre-commit/identify/blob/master/identify/extensions.py

**Comment by thibaudcolas** [comment]
Thank you @imomaliev, that makes sense to me. I’ve made PRs to add support for Nunjucks and Liquid: https://github.com/pre-commit/identify/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Athibaudcolas.

**Review by thibaudcolas — APPROVED** [review]
`identify` / `pre-commit` now has support for all the desired file types in `types_or`, so I believe this is good to go.

**Pull request merged**
